spring.application.name=ms_notificaciones
spring.datasource.url=jdbc:postgresql://localhost:5432/ms_notificaciones
spring.datasource.username=postgres
spring.datasource.password=30806740*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8083

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=eb67d80bc40b14
spring.mail.password=efc4daf96a2e44
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true